name: Surya Karuna
favicon: null
layout_spectrum: 0.8434788179583848
typography_spectrum: 0.1247728755697608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8553309892304242
  lightness: 0.38472319836728275
  saturation: 0.734181001316756
  rhythmicContrast: 0.31057799654081464
purpose: []
