name: Surya Karuna
favicon: null
layout_spectrum: 0.50571
typography_spectrum: 0.75061
title: Surya
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#476291'
    - '#c4e4fb'
    - '#3d2521'
    - '#c4b8ac'
    - '#ea6714'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
